propiedades_zona:
    path:     /
    defaults: { _controller: "AcmePropiedadesBundle:Zona:index" }

propiedades_zona_show:
    path:     /{id}/show
    defaults: { _controller: "AcmePropiedadesBundle:Zona:show" }

propiedades_zona_new:
    path:     /new
    defaults: { _controller: "AcmePropiedadesBundle:Zona:new" }

propiedades_zona_create:
    path:     /create
    defaults: { _controller: "AcmePropiedadesBundle:Zona:create" }
    requirements: { _method: post }

propiedades_zona_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmePropiedadesBundle:Zona:edit" }

propiedades_zona_update:
    path:     /{id}/update
    defaults: { _controller: "AcmePropiedadesBundle:Zona:update" }
    requirements: { _method: post|put }

propiedades_zona_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmePropiedadesBundle:Zona:delete" }
    #requirements: { _method: post|delete }
